services:
  caddy:
    image: caddy:2.9
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./caddy/data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/templates:/srv

  sing-box:
    image: ghcr.io/sagernet/sing-box:v1.11.13
    restart: always
    command: -D /var/lib/sing-box -C /etc/sing-box/ run sing-box
    ports:
      - "443:443"
    volumes:
      - ./sing-box:/etc/sing-box/
